### ISSUE TITLE
cv2 error when running realtime.py

### ISSUE THREAD

**Issue by Dyex719** [Tony607/Keras_age_gender#4]
When I run
`python realtime_demo.py `

I get an error:
cv2.error: OpenCV(3.4.1) /io/opencv/modules/objdetect/src/cascadedetect.cpp:1698: error: (-215) !empty() in function detectMultiScale

**Comment by Dyex719** [comment]
This can be rectified by changing `CASE_PATH` in the realtime.py file to be the absolute path to the file 
haarcascade_frontalface_alt.xml.

Set:
`CASE_PATH = "/home/user/path_to_dir/Keras_age_gender/pretrained_models/haarcascade_frontalface_alt.xml"
`

**Comment by Tony607** [comment]
Thanks for sharing!
